const tableName = "users";

const seed = async function (knex) {
  await knex(tableName).truncate();
  await knex(tableName).insert([
    {
      email: "admin@admin.com",
      firstname: "admin",
      lastname: "admin",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 1,
      receive_notifications: false,
    },
    {
      email: "user@user.com",
      firstname: "user",
      lastname: "user",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "John",
      lastname: "Pork",
      email: "john.pork@gmail.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Tim",
      lastname: "Cheese",
      email: "tim.cheese@gmail.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "SpongeBob",
      lastname: "SquarePants",
      email: "spongebob.squarepants@bikinibottom.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Joe",
      lastname: "Biden",
      email: "joe.biden@whitehouse.gov",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Ballerina",
      lastname: "Cappuccina",
      email: "ballerina.cappuccina@dance.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Donald",
      lastname: "Trump",
      email: "donald.trump@trump.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Jesse",
      lastname: "Pinkman",
      email: "jesse.pinkman@breakingbad.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Rick",
      lastname: "Astley",
      email: "rick.astley@nevergonnagiveyouup.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Walter",
      lastname: "White",
      email: "walter.white@heisenberg.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Tung",
      lastname: "Sahur",
      email: "tung.sahur@example.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Elon",
      lastname: "Musk",
      email: "elon.musk@tesla.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 3,
      receive_notifications: true,
    },
    {
      firstname: "Arthur",
      lastname: "Morgan",
      email: "arthur.morgan@rdr2.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Will",
      lastname: "Smith",
      email: "will.smith@freshprince.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 3,
      receive_notifications: true,
    },
    {
      firstname: "Drake",
      lastname: "Graham",
      email: "drake.graham@ovo.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Andrew",
      lastname: "Tate",
      email: "andrew.tate@cobratate.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Shrek",
      lastname: "Evergreen",
      email: "shrek.evergreen@swamp.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Macky",
      lastname: "Gee",
      email: "macky.gee@dnb.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Peter",
      lastname: "Griffin",
      email: "peter.griffin@familyguy.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Dwayne",
      lastname: "Johnson",
      email: "dwayne.johnson@therock.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
    {
      firstname: "Shaggy",
      lastname: "Rogers",
      email: "shaggy.rogers@scoobydoo.com",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: false,
    },
    {
      firstname: "Napoleon",
      lastname: "Bonaparte",
      email: "napoleon.bonaparte@france.fr",
      password: "$2b$10$n16oFtT47azzzQKjsKQj9.qwDn5Tn9xLcK5bJKqZIVsAQjiNvPs4S",
      role_id: 2,
      receive_notifications: true,
    },
  ]);
};

export { seed };
